### PR TITLE
Updated package dependency on latest symfony/yaml 

### PR DESCRIPTION
**Pull request by true-timmo**
Thanks for sharing your active-directory package. Good work 👍

### CODE REVIEW

**Comment by kschroeder** [comment]
@trivago-timmo Thanks for the PR.  What's the purpose of removing PHP 7.0 support?

**Comment by true-timmo** [comment]
@kschroeder By upgrading the package dependency on symfony/yaml to ^4.0 I kind of excluded php < 7.0. symfony uses the new nullable hinting feature that was introduced in php 7.1, so unfortunately symfony/yaml is not backward compatible and symfony/yaml 4.x is required by my application.

Would you consider a major release for this changeset?

**Comment by kschroeder** [comment]
@trivago-timmo My preference would be to, instead, make `symfony/yaml` a suggested package instead of a required package.  I would rather not break compatibility on a supported version of PHP if I can avoid it.

**Comment by kschroeder** [comment]
I don't recall YAML being a required feature so I should have just done that to begin with when I first wrote this.

**Comment by true-timmo** [comment]
@kschroeder Hmm, as far as I see, you are using the package in the implenentation of `lib/Config/Repository/YamlConfigurationRepository.php`. That's why I had to upgrade php, because of a failing test ;-)

**Comment by kschroeder** [comment]
@trivago-timmo Correct, I use it with the `YamlConfigurationRepository` class.  But that is there as a helper *IF* someone wants to use Yaml.  If you were upgrading because of a failing test from my package then, rather than update the whole thing, I prefer marking `symfony/yaml` as optional and update the test to do a `class_exists()` check for the Symfony Yaml and mark the test as skipped if the class cannot be found.

**Comment by true-timmo** [comment]
Sorry für die vermurxte commit message 😂

**Pull request merged**
